<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:fmi-ls="http://fmi-standard.org/fmi-ls-manifest"
            elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:import  namespace="http://fmi-standard.org/fmi-ls-manifest"
                schemaLocation="https://raw.githubusercontent.com/modelica/fmi-standard/v3.0.1/schema/fmi3LayeredStandardManifest.xsd"/>

    <xs:annotation>
		<xs:documentation source="https://github.com/boschglobal/dse.standards/blob/main/LICENSE">
            SPDX-FileCopyrightText: 2026 Robert Bosch GmbH
            SPDX-License-Identifier: Apache-2.0
            SPDX-PackageName: com.github.boschglobal.dse.fmi-ls-sequential-vr
            SPDX-PackageSupplier: Robert Bosch GmbH
        </xs:documentation>
	</xs:annotation>

    <xs:simpleType name="ActivationEnum">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
            <xs:enumeration value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="fmiLayeredStandardManifest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SequentialVr" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ActivationParameter" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                    <xs:attribute name="type" type="xs:string" use="required" fixed="Integer"/>
                                    <xs:attribute name="value" type="ActivationEnum" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <xs:attribute ref="fmi-ls:fmi-ls-name" use="required" fixed="com.github.boschglobal.dse.fmi-ls-sequential-vr"/>
            <xs:attribute ref="fmi-ls:fmi-ls-version" use="required"/>
            <xs:attribute ref="fmi-ls:fmi-ls-description" use="optional"/>
        </xs:complexType>
    </xs:element>
</xs:schema>
